import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("layout_optimizer", ROOT / "layout_optimizer.py")
assert spec and spec.loader
module = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = module
spec.loader.exec_module(module)


class ProfileSafetyTests(unittest.TestCase):
    def test_rejected_profile_is_refused_by_default(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rejected.json"
            path.write_text(json.dumps({
                "_status": "REJECTED - unusable",
                "_rejected_because": ["bad capture"],
            }))
            with self.assertRaises(SystemExit) as ctx:
                module.load_profile(path)
            self.assertIn("REJECTED", str(ctx.exception))
            self.assertIn("--allow-rejected-profile", str(ctx.exception))

    def test_rejected_status_check_is_case_insensitive(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rejected.json"
            path.write_text(json.dumps({"_status": "rejected - unusable"}))
            with self.assertRaises(SystemExit):
                module.load_profile(path)

    def test_accepted_profile_is_loaded(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "accepted.json"
            path.write_text(json.dumps({
                "_status": "ACCEPTED - generated by rom_capture.py",
                "pad_mm": [224, 148],
            }))
            self.assertEqual(module.load_profile(path)["_status"],
                             "ACCEPTED - generated by rom_capture.py")

    def test_apply_profile_also_refuses_rejected_status(self):
        with self.assertRaises(ValueError):
            module.apply_profile({"_status": "REJECTED - unusable"})

    def test_rejected_override_requires_diagnostic_source_label(self):
        with self.assertRaises(ValueError):
            module.apply_profile(
                {"_status": "REJECTED - unusable"},
                allow_rejected=True,
            )
        module.apply_profile(
            {"_status": "REJECTED - unusable"},
            source="rejected hand profile (diagnostic)",
            allow_rejected=True,
        )

    def test_explicit_diagnostic_override_is_available(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rejected.json"
            path.write_text(json.dumps({"_status": "REJECTED - unusable"}))
            self.assertEqual(module.load_profile(path, allow_rejected=True)["_status"],
                             "REJECTED - unusable")


if __name__ == "__main__":
    unittest.main()
