#!/usr/bin/env python3
"""Is 0.4583 a signal in the hand, or an artifact of a 57-dimensional descriptor scored
over 24 points? A permutation null test, decided before the numbers are known.

THE NUMBER UNDER TEST
    scripts/field_separability.py reports class-mean top-1 = 0.4583 for the
    permutation-invariant ten-contact field descriptor, against a 0.1250 chance level
    for 8 compass classes. That is the only positive result in the project. It has
    never been tested against a null.

THE NULL HYPOTHESIS, IN WORDS
    That the descriptor separates ARBITRARY labels as well as it separates the real
    ones. A nearest-class-mean over 57 z-scored features fitted on 24 points can be
    pushed well above chance by the dimensionality alone. The null is generated by
    permuting the eight compass class labels across the same 24 trials and re-running
    the same classifier on the same descriptors: the descriptors, the classifier, the
    trial count, the class sizes and the class count are all held fixed, so the only
    thing that changes is whether the label carries information. If the shuffled
    labels also score 0.4583, then 0.4583 is the descriptor's own bias and not evidence
    about the hand.

    The 0.1250 "chance level" that field_separability.py prints is 1/K, a nominal
    label prior. It is NOT the right reference for this classifier, because eight
    class means are fitted on twenty-four points in fifty-seven dimensions, and that
    fits noise on its own. The permutation null below is the right reference, and it
    is much higher than 0.1250. A descriptor that scores 0.4583 therefore cannot be
    read as "3.7 times chance" without the null next to it.

DECISION RULE, FIXED BEFORE ANY NUMBER IS PRINTED
    The p-value is one-sided: the fraction of permutations scoring at or above the
    observed value, which is exactly the probability of seeing the observed result or
    better under the null. alpha = 0.05.

    Branch 1 - WITHDRAW. If p >= 0.05, the observed accuracy is not distinguishable
    from the permutation null. The 0.4583 must then be withdrawn as evidence, and
    every document that cites it as the surviving signal must be corrected, because
    the sentence "the field descriptor separates the compass classes" would be false.

    Branch 2 - NOT SUFFICIENT. If p < 0.05, beating the null is necessary but NOT
    sufficient evidence. 24 trials from one hand in one session by one operator, with
    thumb-compass labels and no error bars, still cannot support a claim about field
    gestures. The controlled reshaping experiment has never run. Branch 2 licenses
    the sentence "the observed accuracy exceeds what label permutations of this
    descriptor produce", and nothing stronger.

    The rule is the same for the synthetic control below, but the VERDICT line is
    driven by the real capture only. The synthetic run is there so a reader can see
    the chance level this descriptor dimensionality produces when the point clouds
    carry no hand in them at all.

PERMUTATIONS
    1000 by default. A permutation test cannot resolve a p-value finer than 1/B, and
    the decision threshold is 0.05, so B = 1000 buys three orders of magnitude of
    resolution in the tail that the decision does not even use, while keeping the
    run to a few minutes of pure Python on 24 trials. At n = 1000 the standard error
    of the null mean is at most 0.016, and far smaller in the tail. A reported
    p-value of 0.0000 therefore means "fewer than 1 permutation in 1000 reached the
    observed value", not "p = 0 exactly". Use --permutations to change B.

WHAT IS AND IS NOT BEING TESTED
    The descriptor is permutation-invariant by construction: contact order, TID,
    major, minor and orientation are excluded because those were the quantities the
    gate measurements disqualified. So the only question here is whether the
    descriptor separates THESE labels better than chance, and this test cannot speak
    to any other design decision.

PROVENANCE
    Every line this script prints carries the provenance of the capture it is talking
    about. There is exactly one real capture in this project and it is small; nothing
    here is a population result.

Usage:
    python3 scripts/field_null_test.py \
        --session ../session-stand/messung/s12.jsonl \
        --manifest ../session-stand/messung/s12.manifest.jsonl
    python3 scripts/field_null_test.py --session s12.jsonl --manifest s12.manifest.jsonl \
        --permutations 5000 --seed 7
"""
from __future__ import annotations

import argparse
import json
import math
import random
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import field_separability as sep  # noqa: E402  (reused, never copied)

PROVENANCE = ("[provenance: 24 measured cued trials | 8 compass classes | 3 per class | "
              "one operator | one session | n=63 strokes | thumb-compass labels | "
              "no error bars]")

EXPECTED_TRIALS = 24
EXPECTED_CLASSES = 8
DEFAULT_PERMUTATIONS = 1000
DEFAULT_SEED = 20260925
DEFAULT_ALPHA = 0.05
# Ten contacts, the real capture's own extent in its own units. Scale barely matters
# (the descriptor normalises by spread and by mean pairwise distance), but matching it
# keeps the synthetic control comparable rather than merely smaller.
SYNTH_POINTS = 10
SYNTH_EXTENT = (200.0, 125.0)


def emit(text: str) -> None:
    """Print one line, always with the capture's provenance attached."""
    print(f"{text}  {PROVENANCE}")


def build_trials(session: Path, manifest: Path | None):
    """Scoreable (label, descriptor) pairs from a cued capture.

    Same selection rule as field_separability.py: skip practice cues, take the cue
    window, and use the fullest frame in it rather than the last one, because the last
    frame of a window is the lift-off where the field is empty. The descriptor itself
    is imported, not reimplemented.
    """
    frames, cues = sep.load(session, manifest)
    if not frames:
        raise ValueError("the capture is empty: the device reported no contacts at all")
    if not cues:
        raise ValueError("no manifest with cued labels; there is nothing to label")
    trials = []
    for cue in cues:
        if cue.get("practice"):
            continue
        a, b = cue.get("t_start"), cue.get("t_end")
        if a is None or b is None:
            continue
        window = [(t, p) for t, p in frames if a <= t <= b]
        if len(window) < 3:
            continue
        peak = max(window, key=lambda tp: (len(tp[1]), tp[0]))[1]
        vec = sep.descriptor(peak)
        if vec is None:
            continue
        trials.append((cue.get("label") or cue.get("sector") or "?", vec))
    # Sorted by label so that the classifier's tie-breaking cannot depend on the order
    # a permutation happens to produce. Stable, so within-class order is unchanged.
    return sorted(trials, key=lambda t: t[0])


def class_mean_top1(trials):
    """Nearest-class-mean top-1 accuracy, from the classifier field_separability uses."""
    return sep.evaluate_classifier(trials)["nearest_class_mean_top1"]


def permuted_labels(labels, n_perm: int, seed: int):
    """n_perm independent shuffles of labels, deterministic for a fixed seed."""
    rng = random.Random(seed)
    out = []
    for _ in range(n_perm):
        shuffled = list(labels)
        rng.shuffle(shuffled)
        out.append(tuple(shuffled))
    return out


def null_distribution(trials, n_perm: int, seed: int):
    """Class-mean top-1 over n_perm label permutations of the same descriptors."""
    labels = [label for label, _ in trials]
    descs = [vec for _, vec in trials]
    return [class_mean_top1(list(zip(plabels, descs)))
            for plabels in permuted_labels(labels, n_perm, seed)]


def one_sided_p_value(null, observed: float) -> float:
    """Fraction of permutations at or above the observed value."""
    if not null:
        raise ValueError("empty null distribution")
    return sum(1 for a in null if a >= observed) / len(null)


def quantile(sorted_values, q: float) -> float:
    """Nearest-rank quantile of an already sorted sequence. q in [0, 1]."""
    if not sorted_values:
        raise ValueError("empty sequence")
    if not 0.0 <= q <= 1.0:
        raise ValueError(f"quantile out of range: {q}")
    rank = max(1, math.ceil(q * len(sorted_values)))
    return sorted_values[min(rank, len(sorted_values)) - 1]


def synthetic_trials(n_trials: int, n_classes: int, seed: int):
    """Descriptors of random point clouds: no hand, no class structure, same sizes."""
    rng = random.Random(seed + 1)
    width, height = SYNTH_EXTENT
    per_class = n_trials // n_classes
    trials = []
    for i in range(n_trials):
        pts = [(rng.uniform(0.0, width), rng.uniform(0.0, height))
               for _ in range(SYNTH_POINTS)]
        vec = sep.descriptor(pts)
        if vec is None:
            continue
        trials.append((f"c{i % n_classes}", vec))
    assert len(trials) == n_trials and per_class >= 1
    return sorted(trials, key=lambda t: t[0])


def verdict(branch: str, p: float, alpha: float) -> str:
    """One line naming the branch of the pre-registered decision rule that applies."""
    if branch == "withdraw":
        return (f"VERDICT: WITHDRAW - p = {p:.4f} >= alpha = {alpha:.2f}, the observed "
                "accuracy is not distinguishable from shuffled labels; 0.4583 must be "
                "withdrawn as evidence and every document citing it as the surviving "
                "signal must be corrected")
    return (f"VERDICT: NOT SUFFICIENT - p = {p:.4f} < alpha = {alpha:.2f}, the observed "
            "accuracy exceeds the permutation null; that is necessary but not "
            "sufficient, because 24 trials from one hand in one session still cannot "
            "support a claim about field gestures and the control experiment has never "
            "run")


def report(tag: str, observed: float, null, alpha: float, seconds: float) -> tuple:
    """Print the observed value, the null's quantiles and the p-value for one branch."""
    ordered = sorted(null)
    mean = sum(ordered) / len(ordered)
    p = one_sided_p_value(null, observed)
    emit(f"{tag} observed class-mean top-1   {observed:.4f}")
    emit(f"{tag} null mean                   {mean:.4f}")
    emit(f"{tag} null median                 {quantile(ordered, 0.5):.4f}")
    emit(f"{tag} null 95th percentile        {quantile(ordered, 0.95):.4f}")
    emit(f"{tag} null 99th percentile        {quantile(ordered, 0.99):.4f}")
    emit(f"{tag} null min / max             {ordered[0]:.4f} / {ordered[-1]:.4f}")
    emit(f"{tag} permutations B             {len(null)} "
         f"({seconds / len(null):.3f} s each, {seconds:.1f} s total)")
    emit(f"{tag} one-sided p-value          {p:.4f}  "
         f"(fraction at or above observed; 0.0000 means fewer than 1 in {len(null)})")
    return p, {"observed": observed, "null_mean": mean,
               "null_median": quantile(ordered, 0.5),
               "null_q95": quantile(ordered, 0.95),
               "null_q99": quantile(ordered, 0.99),
               "null_min": ordered[0], "null_max": ordered[-1],
               "permutations": len(null), "p_value": p, "seconds": seconds}


def main() -> int:
    ap = argparse.ArgumentParser(description="Permutation null test for 0.4583.")
    ap.add_argument("--session", type=Path, required=True)
    ap.add_argument("--manifest", type=Path)
    ap.add_argument("--permutations", type=int, default=DEFAULT_PERMUTATIONS)
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument("--alpha", type=float, default=DEFAULT_ALPHA)
    ap.add_argument("--json", type=Path)
    args = ap.parse_args()

    emit("=" * 60)
    emit("PERMUTATION NULL TEST - the only positive result in this project")
    emit("null hypothesis: the descriptor separates arbitrary labels as well as the real ones")
    emit(f"decision rule:   p >= {args.alpha:.2f} -> WITHDRAW 0.4583 as evidence; "
         f"p < {args.alpha:.2f} -> beats the null, necessary but NOT sufficient")
    emit(f"seed             {args.seed}   permutations {args.permutations}")
    emit("=" * 60)

    try:
        trials = build_trials(args.session, args.manifest)
    except ValueError as exc:
        emit(f"cannot run: {exc}")
        return 2
    if not trials:
        emit("cannot run: no scoreable trials in the capture")
        return 2
    classes = sorted({label for label, _ in trials})
    K = len(classes)
    chance = 1.0 / K
    emit(f"session          {args.session.name}")
    emit(f"trials/classes   {len(trials)} / {K}   descriptor dim {len(trials[0][1])}")
    emit(f"chance           {chance:.4f}  ({chance:.1%})")
    if len(trials) != EXPECTED_TRIALS or K != EXPECTED_CLASSES:
        emit(f"WARNING: the provenance line above describes the s12 capture; this run "
             f"scored {len(trials)} trials in {K} classes, so it does not apply to it")

    t0 = time.time()
    observed = class_mean_top1(trials)
    null = null_distribution(trials, args.permutations, args.seed)
    real_p, real_res = report("real   ", observed, null, args.alpha, time.time() - t0)

    emit("-" * 60)
    emit("SYNTHETIC CONTROL - random point clouds, same count, same contact count")
    emit("no hand and no class structure are present, so this is the chance level that")
    emit("this descriptor dimensionality produces on its own, independent of the capture")
    t0 = time.time()
    syn = synthetic_trials(len(trials), K, args.seed)
    syn_observed = class_mean_top1(syn)
    syn_null = null_distribution(syn, args.permutations, args.seed)
    syn_p, syn_res = report("synth  ", syn_observed, syn_null, args.alpha,
                            time.time() - t0)
    emit(f"note: the nominal 1/K chance level of {chance:.4f} is a label prior, not this")
    emit(f"classifier's null; the synthetic control above is the chance level that a "
         f"{len(trials[0][1])}-dimensional descriptor on {len(trials)} points produces "
         f"with no hand in it at all")

    emit("-" * 60)
    branch = "withdraw" if real_p >= args.alpha else "survives"
    emit(verdict(branch, real_p, args.alpha))
    if branch == "withdraw":
        emit("consequence: DESIGN_DECISION_FINAL.md, VERTICAL_SLICE.md, ARCHIVE.md and "
             "MEASURED_REJECTION.md all cite 0.4583 as the surviving signal; the verdict "
             "line above is the correction those documents need")
    else:
        emit("consequence: the ten-contact design space stays open as a hypothesis, not "
             "as a validated concept; no WPM, decoder or gesture claim follows from this")
    emit("this test says nothing about contact order, TID, major, minor or orientation: "
         "the descriptor excludes all of them by construction")
    emit("=" * 60)

    if args.json:
        res = {"session": str(args.session), "seed": args.seed, "alpha": args.alpha,
               "trials": len(trials), "classes": K, "chance": chance,
               "provenance": PROVENANCE, "real": real_res, "synthetic": syn_res,
               "branch": branch, "verdict": verdict(branch, real_p, args.alpha)}
        args.json.write_text(json.dumps(res, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
